<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Authors>Rafael Fraga</Authors>
		<Company>Rafael Fraga</Company>
		<Version>4.0.1</Version>
		<PackageTags>database, mongodb, nosql, components.domain.mongodb</PackageTags>
		<IncludeSymbols>False</IncludeSymbols>
		<Title>DotnetBaseKit.Components.Domain.MongoDb</Title>
		<Description>Creates base configurations for MongoDB in Domain Layer</Description>
		<PackageRequireLicenseAcceptance>False</PackageRequireLicenseAcceptance>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageReleaseNotes>
			- 4.0.1: Adds package release notes
			- Uses centralized package version management
			- Support for net8.0
		</PackageReleaseNotes>
	</PropertyGroup>

	<ItemGroup>
        <PackageReference Include="FluentValidation" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\DotnetBaseKit.Components.Shared\DotnetBaseKit.Components.Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="README.md">
			<PackagePath>\</PackagePath>
			<Pack>True</Pack>
		</None>
	</ItemGroup>

</Project>
